### ISSUE TITLE
GNU/Linux version ??

### ISSUE THREAD

**Issue by cpcbegin** [rcmolina/C64TZX#1]
Is possible to compile these tools for use in GNU/Linux?

**Comment by rcmolina** [comment]
Hi cpcbegin,
The procedure is a combination of 3 programs:
1) audiotap from Frabricio Gennaro. Here:
https://wav-prg.sourceforge.io/audiotap.html
You should ask Fabricio, I compiled this under win. May be it can work with Wine.
DesUbikado (passwd away) made an script. Read more here:
https://web.archive.org/web/20240530121334/http://desubikado.sytes.net/2020/12/30/comodoro-script-y-la-carga-por-audio-en-el-zx-uno-para-maquinas-commodore-8-bits/

2) sox. It's ported already. My own version is a trimmed one for easy compiling and smaller file size.
3) direct fron Tomas Katz. A single file, trivial.
Source already here:
https://github.com/rcmolina/z802tzx3/blob/master/DIRECT.C

**Comment by cpcbegin** [comment]
Thanks for the information.
